resolver: lts-12.0

packages:
- xmobar-git
- xmonad-git
- xmonad-contrib-git

extra-deps:
- parsec-numbers-0.1.0
- X11-1.8
- alsa-mixer-0.2.0.3
- iwlib-0.1.0

flags:
  xmobar:
    all_extensions: true

# packages:
# - some-directory
# - https://example.com/foo/bar/baz-0.0.2.tar.gz
# - location:
#    git: https://github.com/commercialhaskell/stack.git
#    commit: e7b331f14bcffb8367cd58fbfc8b40ec7642100a
# - location: https://github.com/commercialhaskell/stack/commit/e7b331f14bcffb8367cd58fbfc8b40ec7642100a
#  subdirs:
#  - auto-update
#  - wai

#- location:
#    git: https://github.com/xmonad/xmonad
#    commit: ecf1a0ca0d094c76a18c2c1b77ac7c1dcac10f5e
#- location:
#    git: https://github.com/xmonad/xmonad-contrib
#    commit: a4b430bfa7d7c5ad33dd98afe6b6f91d54828c36
#- location:
#    git: https://github.com/jaor/xmobar
#    commit: 11fa52601bc486b110252b7c6aa22bae2bafbd86
