#!/bin/sh
repo="$HOME/repos/github/xmonad-stack"
cd $repo || { echo "could not enter source"; exit 1; }

exec stack --stack-yaml "$repo/stack.yaml" ghc -- \
  --make ~/.xmonad/xmonad.hs \
  -i \
  -ilib \
  -fforce-recomp \
  -main-is main \
  -v0 \
  -o "$1"
